SocialNetApp/Models/ViewModel/PublicacionViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace SocialNetApp.Models.ViewModel

{
    public class PublicacionViewModel
    {
        public int PublicacionId { get; set; }
        [Required]
        public string Contenido { get; set; }
        public DateTime FechaPublicacion { get; set; }
        public int UsuarioId { get; set; }
        public int EstadoPublicacion { get; set; }
    }


    public class EditPublicacionViewModel
    {
        public int PublicacionId { get; set; }
        [Required]
        public string Contenido { get; set; }
        public DateTime FechaPublicacion { get; set; }
        public int UsuarioId { get; set; }
        public int EstadoPublicacion { get; set; }
    }


    public class PublicacionNamesViewModel
    {
        public int PublicacionId { get; set; }
        [Required]
        public string Contenido { get; set; }
        public DateTime FechaPublicacion { get; set; }
        public int UsuarioId { get; set; }
        public string NombreUsuario { get; set; }
        public string ApellidoUsuario { get; set; }
        public int EstadoPublicacion { get; set; }
    }
}

SocialNetApp/Controllers/ComentarioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SocialNetApp.Models;
using SocialNetApp.Models.TableViewModel;
using SocialNetApp.Models.ViewModel;

namespace SocialNetApp.Controllers
{
    public class ComentarioController : Controller
    {
        // GET: Comentario
        public ActionResult Index()
        {
            return View();
        }


        [HttpPost]
        public ActionResult Add(string ContenidoComentario, string IdPublicacion)
        {
            var userid = Convert.ToInt32(Session["UserId"].ToString());
            var PublicacionId = Convert.ToInt32(IdPublicacion);
            using (var db = new SOCIALEntities1())
            {
                Comentarios oComentario = new Comentarios();

                oComentario.Contenido = ContenidoComentario;
                oComentario.UsuarioId = userid;
                oComentario.PublicacionId = PublicacionId;
                oComentario.EstadoComentario = 1;
                oComentario.FechaHoraComentario = DateTime.Now;

                db.Comentarios.Add(oComentario);
                db.SaveChanges();
            }
            //return Redirect(Url.Content("~/Publicacion/DetallePublicacion"));

            return Redirect(Url.Content("~/Publicacion/DetallePublicacion") + "/" +PublicacionId);


        }
    }
}

SocialNetApp/Controllers/PublicacionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using SocialNetApp.Models;
using SocialNetApp.Models.TableViewModel;
using SocialNetApp.Models.ViewModel;

namespace SocialNetApp.Controllers
{
    public class PublicacionController : Controller
    {
        // GET: Publicacion
        //public ActionResult Index()
        //{
        //    List<PublicacionesEditViewModel> lst = null;
        //    using (SOCIALEntities1 db = new SOCIALEntities1())
        //    {
        //        lst = (from d in db.Publicaciones
        //               select new PublicacionesEditViewModel
        //               {
        //                   PublicacionId = d.PublicacionId,
        //                   Contenido = d.Contenido,
        //                   FechaPublicacion = d.FechaHoraPublicacion,
        //                   UsuarioId = d.UsuarioId,
        //               }).ToList();
        //    }
        //    return View(lst);
        //}

        public ActionResult Index()
        {
            //List<PublicacionesEditViewModel> lst = null;
            List<PublicacionNamesViewModel> publicacionesAmigos = null;
            //List<Publicaciones> publicacionesAmigos = null;
            var userid = Convert.ToInt32(Session["UserId"].ToString());
            using (SOCIALEntities1 db = new SOCIALEntities1())
            {
                var amigos = (from a in db.Amistades
                              where (a.UsuarioAceptadoId == userid && a.EstadoAmistad == 2) || (a.UsuarioSolicitanteId == userid && a.EstadoAmistad == 2)
                              select new { UsuarioId = (a.UsuarioAceptadoId == userid ? a.UsuarioSolicitanteId : a.UsuarioAceptadoId) }).Distinct();

                publicacionesAmigos = (from d in db.Publicaciones
                                       join amigo in amigos on d.UsuarioId equals amigo.UsuarioId
                                       join u in db.Usuarios on d.UsuarioId equals u.UsuarioId
                                       where d.EstadoPublicacion == 1
                                       select new PublicacionNamesViewModel
                                       {
                           PublicacionId = d.PublicacionId,
                           Contenido = d.Contenido,
                           FechaPublicacion = d.FechaHoraPublicacion,
                           UsuarioId = d.UsuarioId,
                           NombreUsuario = u.NombreUsuario,
                           ApellidoUsuario = u.ApellidoUsuario
                           
                       }).Distinct().ToList();
            }
            return View(publicacionesAmigos);
        }


        public ActionResult MisPublicaciones()
        {
            List<PublicacionNamesViewModel> lst = null;
            var userid = Convert.ToInt32(Session["UserId"].ToString());
            using (SOCIALEntities1 db = new SOCIALEntities1())
            {
                lst = (from d in db.Publicaciones
                       join u in db.Usuarios on d.UsuarioId equals u.UsuarioId
                       where d.UsuarioId == userid &&d.EstadoPublicacion == 1
                       select new PublicacionNamesViewModel
                       {
                           PublicacionId = d.PublicacionId,
                           Contenido = d.Contenido,
                           FechaPublicacion = d.FechaHoraPublicacion,
                           UsuarioId = d.UsuarioId,
                           NombreUsuario = u.NombreUsuario,
                           ApellidoUsuario = u.ApellidoUsuario
                       }).ToList();
            }
            return View(lst);
        }


        [HttpGet]
        public ActionResult PublicacionAmigo(int Id)
        {
            List<PublicacionViewModel> lst = null;            
            using (SOCIALEntities1 db = new SOCIALEntities1())
            {
                lst = (from d in db.Publicaciones
                       where d.UsuarioId == Id
                       select new PublicacionViewModel
                       {
                           PublicacionId = d.PublicacionId,
                           Contenido = d.Contenido,
                           FechaPublicacion = d.FechaHoraPublicacion,
                           UsuarioId = d.UsuarioId,
                       }).ToList();
            }
            //return View("~/Views/Publicacion/Index.cshtml", lst);
            return View(lst);
        }


        [HttpPost]
        public ActionResult Add(string ContenidoPublicacion)
        {
            var userid = Convert.ToInt32(Session["UserId"].ToString());
            using (var db = new SOCIALEntities1())
            {
                Publicaciones oPublicacion = new Publicaciones();

                oPublicacion.Contenido = ContenidoPublicacion;
                oPublicacion.UsuarioId = userid;
                oPublicacion.EstadoPublicacion = 1;
                oPublicacion.FechaHoraPublicacion = DateTime.Now;


                db.Publicaciones.Add(oPublicacion);
                db.SaveChanges();
            }
            return Redirect(Url.Content("~/Publicacion/MisPublicaciones"));
        }



        [HttpGet]
        public ActionResult DetallePublicacion(int Id)
        {
            ViewData["PublicacionId"] = Id;


            List<PublicacionNamesViewModel> lst = null;
            List <ComentarioNameViewModel> lstComment = null;
            using (SOCIALEntities1 db = new SOCIALEntities1())
            {
                lst = (from d in db.Publicaciones
                       where d.PublicacionId == Id
                       join u in db.Usuarios on d.UsuarioId equals u.UsuarioId
                       select new PublicacionNamesViewModel
                       {
                           PublicacionId = d.PublicacionId,
                           Contenido = d.Contenido,
                           FechaPublicacion = d.FechaHoraPublicacion,
                           UsuarioId = d.UsuarioId,
                           NombreUsuario = u.NombreUsuario,
                           ApellidoUsuario = u.ApellidoUsuario
                       }).ToList();

                ViewData["UsuarioId"] = lst[0].UsuarioId;
                ViewData["Contenido"] = lst[0].Contenido;
                ViewData["FechaPublicacion"] = lst[0].FechaPublicacion;
                ViewData["NombreUsuario"] = lst[0].NombreUsuario;
                ViewData["ApellidoUsuario"] = lst[0].ApellidoUsuario;

                lstComment = (from d in db.Comentarios
                              where d.PublicacionId == Id
                              join u in db.Usuarios on d.UsuarioId equals u.UsuarioId
                              select new ComentarioNameViewModel
                              {
                                  Comentarioid = d.ComentarioId,
                                  Contenido = d.Contenido,
                                  FechaComentario = d.FechaHoraComentario,
                                  UsuarioId = d.UsuarioId,
                                  PublicacionId = d.PublicacionId,
                                  EstadoComentario = d.EstadoComentario,
                                  NombreUsuario = u.NombreUsuario,
                                  ApellidoUsuario = u.ApellidoUsuario

                              }).ToList();

            }
            //return View("~/Views/Publicacion/Index.cshtml", lst);
            return View(lstComment);
            //return Content("1");
        }


        [HttpPost]
        public ActionResult DetallePublicacion(int Id, int UsuarioId, string Contenido, DateTime FechaPublicacion)
        {
            ViewData["PublicacionId"] = Id;
            ViewData["UsuarioId"] = UsuarioId;
            ViewData["Contenido"] = Contenido;
            ViewData["FechaPublicacion"] = FechaPublicacion;

            List<PublicacionViewModel> lst = null;
            using (SOCIALEntities1 db = new SOCIALEntities1())
            {
                lst = (from d in db.Publicaciones
                       where d.PublicacionId == Id
                       select new PublicacionViewModel
                       {
                           PublicacionId = d.PublicacionId,
                           Contenido = d.Contenido,
                           FechaPublicacion = d.FechaHoraPublicacion,
                           UsuarioId = d.UsuarioId,
                       }).ToList();
            }
            //return View("~/Views/Publicacion/Index.cshtml", lst);
            //return View(lst);
            //return Redirect(Url.Content("~/Publicacion/MisPublicaciones/"));
            return Content("1");

            //return Content();
        }


        public ActionResult ComentariosPublicacion(int PublicacionId)
        {
            EditComentarioViewModel model = new EditComentarioViewModel();
            using (var db = new SOCIALEntities1())
            {
                var oComentario = db.Comentarios.Find(PublicacionId);
                model.PublicacionId = oComentario.PublicacionId;
                model.Comentarioid = oComentario.ComentarioId;
                model.EstadoComentario = oComentario.EstadoComentario;
                model.Contenido = oComentario.Contenido;
                model.UsuarioId = oComentario.UsuarioId;
                model.FechaComentario = oComentario.FechaHoraComentario;
            }
            return View(model);
        }




        [HttpPost]
        public ActionResult Delete(int Id)
        {
            using (var db = new SOCIALEntities1())
            {
                var oUser = db.Usuarios.Find(Id);
                oUser.EstadoUsuario = 2; //ELIMINAR
                db.Entry(oUser).State = System.Data.Entity.EntityState.Modified;
                db.SaveChanges();
            }
            return Content("1");
        }


    }
}

SocialNetApp/Views/Publicacion/DetallePublicacion.cshtml
@model List<SocialNetApp.Models.ViewModel.ComentarioNameViewModel>

@{
    ViewBag.Title = "Detalle Publicacion";
}
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<link href="~/Content/css/Feed.css" rel="stylesheet" />

<h2>@ViewBag.Title</h2>

<br />


<div class="container bootdey">
    <div class="col-md-12 bootstrap snippets">
        <div class="panel">
            <div class="panel-body">

                <!-- Newsfeed Content -->
                <!--===================================================-->
                <div class="media-block">

                    <div class="media-body">
                        <div class="mar-btm">
                            <a href="#" class="btn-link text-semibold media-heading box-inline">@ViewData["NombreUsuario"] @ViewData["ApellidoUsuario"]</a>
                            <p class="text-muted text-sm"><i class="fa fa-mobile fa-lg"></i> @ViewData["FechaPublicacion"]</p>
                        </div>
                        <p>@ViewData["Contenido"]</p>
                        <div class="pad-ver">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-default btn-hover-success" href="#"><i class="fa fa-thumbs-up"></i></a>
                                <a class="btn btn-sm btn-default btn-hover-danger" href="#"><i class="fa fa-thumbs-down"></i></a>
                            </div>

                        </div>
                        <hr>

                        <!-- Comments -->
                        <!-- Comments -->

                        @foreach (var oElemento in Model)
                        {

                            <div> 
                                <div class="media-block pad-all">
                                    <div class="media-body">
                                        <div class="mar-btm">
                                            <a href="#" class="btn-link text-semibold media-heading box-inline">@oElemento.NombreUsuario @oElemento.ApellidoUsuario</a>
                                            <p class="text-muted text-sm"><i class="fa fa-mobile fa-lg"></i> @oElemento.FechaComentario</p>
                                        </div>
                                        <p>@oElemento.Contenido</p>
                                        <div class="pad-ver">
                                            <div class="btn-group">
                                                <a class="btn btn-sm btn-default btn-hover-success active" href="#"><i class="fa fa-thumbs-up"></i> You Like it</a>
                                                <a class="btn btn-sm btn-default btn-hover-danger" href="#"><i class="fa fa-thumbs-down"></i></a>
                                            </div>
                                        </div>
                                        <hr>
                                    </div>
                                </div>

                            </div>
                        }


                        <div class="panel-body">
                            <form id="frmPubli" action="@Url.Action("Add", "Comentario")" method="post">
                                <textarea name="ContenidoComentario" class="form-control" rows="2" placeholder="Añade un comentario"></textarea>
                                <input type="hidden" name="IdPublicacion" value="@ViewData["PublicacionId"]" />
                                <div class="mar-top clearfix">
                                    <input type="submit" class="btn btn-sm btn-primary btn-success pull-right" value="Nuevo" ) />
                                </div>
                            </form>
                            @*}*@

                        </div>


                    </div>
                </div>
                <!--===================================================-->
                <!-- End Newsfeed Content -->

            </div>
        </div>
    </div>
</div>

SocialNetApp/Views/Publicacion/Index.cshtml
@model List<SocialNetApp.Models.ViewModel.PublicacionNamesViewModel>

@{
    ViewBag.Title = "Publicaciones de Amigos";
}
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<link href="~/Content/css/Feed.css" rel="stylesheet" />

<h2>@ViewBag.Title</h2>

<br />


<div class="container bootdey">
    <div class="col-md-12 bootstrap snippets">
        <div class="panel">
            <div class="panel-body">
@foreach (var oElemento in Model)
{

                <!-- Newsfeed Content -->
                <!--===================================================-->
                <div class="media-block">
                    
                    <div class="media-body">
                        <div class="mar-btm">
                            <a href="#" class="btn-link text-semibold media-heading box-inline">@oElemento.NombreUsuario  @oElemento.ApellidoUsuario</a>
                            <p class="text-muted text-sm"><i class="fa fa-mobile fa-lg"></i> @oElemento.FechaPublicacion</p>
                        </div>
                        <p>@oElemento.Contenido</p>
                        <div class="pad-ver">
                            <div class="btn-group">
                                <a class="btn btn-sm btn-default btn-hover-success" href="#"><i class="fa fa-thumbs-up"></i></a>
                                <a class="btn btn-sm btn-default btn-hover-danger" href="#"><i class="fa fa-thumbs-down"></i></a>
                            </div>
                            <input onclick="jsVerPublicacion(@oElemento.PublicacionId, @oElemento.UsuarioId , '@oElemento.Contenido.ToString()', '@oElemento.FechaPublicacion' );" type="button" value="Comment" class="btn btn-sm btn-default btn-hover-primary" />
                        </div>
                        <hr>

                        <!-- Comments -->

                    </div>
                </div>
                <!--===================================================-->
                <!-- End Newsfeed Content -->
}
            </div>
        </div>
    </div>
</div>


<script>
    function jsVerPublicacion(PublicacionId, UsuarioId,  Contenido , FechaPublicacion) {

        url = "@Url.Content("~/Publicacion/DetallePublicacion")" + "/" + PublicacionId;

        // Eliminar los espacios en blanco al principio y al final de cada cadena
        PublicacionId = PublicacionId;
        UsuarioId = UsuarioId;
        Contenido = Contenido.trim();
        FechaPublicacion = FechaPublicacion.trim();

        var data = {
            PublicacionId: PublicacionId,
            UsuarioId: UsuarioId,
            Contenido: Contenido,
            FechaPublicacion: FechaPublicacion
        };

                $.post(url, data, function (data)  {

                if(data == "1") {
                    //document.location.href = "@Url.Content("~/Publicacion/DetallePublicacion")" + "/" + PublicacionId
                    document.location.href = url;
                } else {
                    alert ("Ocurio un error :(")
                }
            }
            )
        }
</script>

SocialNetApp/Views/Publicacion/MisPublicaciones.cshtml
@model List<SocialNetApp.Models.ViewModel.PublicacionNamesViewModel>

@{
    ViewBag.Title = "Mis Publicaciones";
}
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<link href="~/Content/css/Feed.css" rel="stylesheet" />

<h2>@ViewBag.Title</h2>

<br />


<div class="container bootdey">
    <div class="col-md-12 bootstrap snippets">
        <div class="panel">


            <div class="panel-body">
                @*@using (Html.BeginForm("Add", "Publicacion", FormMethod.Post, new { role = "form", @class = "" }))
                {*@
                <form id="frmPubli" action="@Url.Action("Add", "Publicacion")" method="post">
                    <textarea name="ContenidoPublicacion" class="form-control" rows="2" placeholder="What are you thinking?"></textarea>
                    <div class="mar-top clearfix">
                        <input type="submit" class="btn btn-sm btn-primary btn-success pull-right" value="Nuevo" ) />
                    </div>
                </form>
                    @*}*@

            </div>
        </div>
        <div class="panel">
            <div class="panel-body">
                @foreach (var oElemento in Model)
                {

                <!-- Newsfeed Content -->
                <!--===================================================-->
                    <div class="media-block">

                        <div class="media-body">
                            <div class="mar-btm">
                                <a href="#" class="btn-link text-semibold media-heading box-inline">@oElemento.NombreUsuario  @oElemento.ApellidoUsuario</a>
                                <p class="text-muted text-sm"><i class="fa fa-mobile fa-lg"></i> @oElemento.FechaPublicacion</p>
                            </div>
                            <p>@oElemento.Contenido</p>
                            <div class="pad-ver">
                                <div class="btn-group">
                                    <a class="btn btn-sm btn-default btn-hover-success" href="#"><i class="fa fa-thumbs-up"></i></a>
                                    <a class="btn btn-sm btn-default btn-hover-danger" href="#"><i class="fa fa-thumbs-down"></i></a>
                                </div>
 
                                <input onclick="jsVerPublicacion(@oElemento.PublicacionId, @oElemento.UsuarioId , '@oElemento.Contenido.ToString()', '@oElemento.FechaPublicacion' );" type="button" value="Comment" class="btn btn-sm btn-default btn-hover-primary" />

                            </div>
                            <hr>

                            <!-- Comments -->

                        </div>
                    </div>
                <!--===================================================-->
                <!-- End Newsfeed Content -->
                }
            </div>
        </div>
    </div>
</div>

<script>
    function jsVerPublicacion(PublicacionId, UsuarioId,  Contenido , FechaPublicacion) {

        url = "@Url.Content("~/Publicacion/DetallePublicacion")" + "/" + PublicacionId;

        // Eliminar los espacios en blanco al principio y al final de cada cadena
        PublicacionId = PublicacionId;
        UsuarioId = UsuarioId;
        Contenido = Contenido.trim();
        FechaPublicacion = FechaPublicacion.trim();

        var data = {
            PublicacionId: PublicacionId,
            UsuarioId: UsuarioId,
            Contenido: Contenido,
            FechaPublicacion: FechaPublicacion
        };

                $.post(url, data, function (data)  {

                if(data == "1") {
                    //document.location.href = "@Url.Content("~/Publicacion/DetallePublicacion")" + "/" + PublicacionId
                    document.location.href = url;
                } else {
                    alert ("Ocurio un error :(")
                }
            }
            )
        }
</script>

SocialNetApp/Views/Publicacion/PublicacionAmigo.cshtml
@model List<SocialNetApp.Models.TableViewModel.PublicacionesEditViewModel>

@{
    ViewBag.Title = "Publicaciones de Amigos";
}
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
<link href="~/Content/css/Feed.css" rel="stylesheet" />

<h2>@ViewBag.Title</h2>

<br />


<div class="container bootdey">
    <div class="col-md-12 bootstrap snippets">
        <div class="panel">
            <div class="panel-body">
                <textarea class="form-control" rows="2" placeholder="What are you thinking?"></textarea>
                <div class="mar-top clearfix">
                    <button class="btn btn-sm btn-primary pull-right" type="submit"><i class="fa fa-pencil fa-fw"></i> Share</button>
                </div>
            </div>
        </div>
        <div class="panel">
            <div class="panel-body">
                @foreach (var oElemento in Model)
                {

                <!-- Newsfeed Content -->
                <!--===================================================-->
                    <div class="media-block">

                        <div class="media-body">
                            <div class="mar-btm">
                                <a href="#" class="btn-link text-semibold media-heading box-inline">@oElemento.UsuarioId</a>
                                <p class="text-muted text-sm"><i class="fa fa-mobile fa-lg"></i> @oElemento.FechaPublicacion</p>
                            </div>
                            <p>@oElemento.Contenido</p>
                            <div class="pad-ver">
                                <div class="btn-group">
                                    <a class="btn btn-sm btn-default btn-hover-success" href="#"><i class="fa fa-thumbs-up"></i></a>
                                    <a class="btn btn-sm btn-default btn-hover-danger" href="#"><i class="fa fa-thumbs-down"></i></a>
                                </div>
                                <a class="btn btn-sm btn-default btn-hover-primary" href="#">Comment</a>
                            </div>
                            <hr>

                            <!-- Comments -->

                        </div>
                    </div>
                <!--===================================================-->
                <!-- End Newsfeed Content -->
                }
            </div>
        </div>
    </div>
</div>